### ISSUE TITLE
Global namespace conflict

### ISSUE THREAD

**Issue by yohanyee** [Mouse-Imaging-Centre/MRIcrotome#13]
https://github.com/Mouse-Imaging-Centre/MRIcrotome/blob/c20fe274662fc665d229aee5f304cf84782d515f/R/gridImage.R#L97

When `map()` is masked by other packages, then this fails. 

For example, when I have the `mclust` package loaded after `tidyverse`, then `map` in the global namespace points to `mclust::map` and results in a cryptic error when trying to plot contours. Can this be changed to `purrr::map`?

**Comment by cfhammill** [comment]
This is #2 in disguise. If we had the dependencies sorted then it would use the package local `map` instead of looking for one in the global environment. Will fix.

Edit:
In the interim you can either reorder your `library` calls so that tidyverse is loaded last, or run `map <- purrr::map` somewhere before your plot calls

**Comment by cfhammill** [comment]
@yohanyee can you try this example again with the new develop branch

```r
devtools::install_github("Mouse-Imaging-Centre/MRIcrotome@develop")
```

**Comment by yohanyee** [comment]
Works great!
