### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/MRIcrotome#2]
So far no dependencies other than `knitr` and `rmarkdown` are listed. From the example it seems like users will need `grid` and some `tidyverse` packages. I'm happy to add those to `DESCRIPTION`. Would you like to depend on all of `tidyverse` or would a few subpackages cover it? I only noticed `purrr` functions on my quick skim.

**Comment by jasonlerch** [comment]
At the moment it only uses map and friends plus pipes. I’ve always loaded the entire tidy verse before using the package, though, but that is probably best ascribed to laziness.

Jason
On Jul 3, 2018, 11:34 AM -0400, Chris Hammill <notifications@github.com>, wrote:

So far no dependencies other than knitr and rmarkdown are listed. From the example it seems like users will need grid and some tidyverse packages. I'm happy to add those to DESCRIPTION. Would you like to depend on all of tidyverse or would a few subpackages cover it? I only noticed purrr functions on my quick skim.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Mouse-2DImaging-2DCentre_MRIcrotome_issues_2&d=DwMCaQ&c=Sj806OTFwmuG2UO1EEDr-2uZRzm2EPz39TfVBG2Km-o&r=HeHbjTJnvHS1LfU-oVbj4xp56MzXc8SwpgPYe318jo0&m=timLKL5A9PtcmEFx4Rf-qtB7rwBWh3i6B_Z1a2_4sR0&s=tnpZ5kAkwHaA0z051chChI9hNkn5-omGQSkqqxfN5e0&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAxd-5F3KfG4YkPUveejzTW-2D78DTTBfSqSks5uC475gaJpZM4VBLb7&d=DwMCaQ&c=Sj806OTFwmuG2UO1EEDr-2uZRzm2EPz39TfVBG2Km-o&r=HeHbjTJnvHS1LfU-oVbj4xp56MzXc8SwpgPYe318jo0&m=timLKL5A9PtcmEFx4Rf-qtB7rwBWh3i6B_Z1a2_4sR0&s=u1i_8SS9AAALuQJUSokfEp2Ko5naGFvRxon9GrMkG5E&e=>.

________________________________

This e-mail may contain confidential, personal and/or health information(information which may be subject to legal restrictions on use, retention and/or disclosure) for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies.

**Comment by cfhammill** [comment]
I think `purrr` imports `%>%` so the tidy dependency footprint could be as small as `purrr`, although if we go for `tidyverse` now there is less impediment to using more tidy tools as the need arises. Your choice.

**Comment by cfhammill** [comment]
For now I've added `grid` and `purrr` as explicit dependencies, we can expand this list as we go.
